version: '2'
services:
    jenkins:
        image: 'jenkins/jenkins:lts'
        container_name: "jenkins"
        labels: 
            Kompose.service.type: nodeport
        ports:
            - '8080:8080'
            - '443:8443'
            - '50000:50000'
        volumes:
            - /home/khadija/projetOdoo/projet_jenkins/srv/data/jenkins_data:/jenkins_home
            - /home/khadija/projetOdoo/projet_jenkins/srv/data/jenkins:/jenkins_config

    Docker:
        image: 'docker:latest'
        container_name: "docker"
    
        volumes:
            - /home/khadija/projetOdoo/projet_jenkins/srv/data/vdocker://var/lib/docker
        
        

volumes:
    jenkins_data:
        driver: local
    jenkins:
        driver: local
    vdocker:
         driver: local
